### ISSUE TITLE
Build with cython

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/distributed-feedstock#152]
I'm sure all the contributors here are across it, but just so the `conda` package doesn't get forgotten, it would be good for `distributed` to be as fast as possible and hence to be built with `cython`

***xref:*** https://github.com/dask/distributed/pull/4292

**Comment by jakirkham** [comment]
Actually I'd recommend holding off on this for a bit. Am saying this for a few reasons:

1. A release is planned for next week and we only started doing this work this week
2. Only a relatively small amount of stuff has been Cythonized in `master` (more to come)
3. Outside of myself and some CI testing, not sure that it has seen broad enough usage yet

For these reasons, it seems reasonable to make this an opt-in thing for now as opposed to opt-out. Given there is a build flag, hopefully it's not too difficult for folks to opt-in.

That all being said, I would like to get more folks to try this and share feedback in the near future. Just not sure we are ready for conda-forge scale of folks trying this yet. Maybe in another release or so that will change. Hope that makes sense 🙂

**Comment by jakirkham** [comment]
As upstream issue ( https://github.com/dask/distributed/issues/4442 ) is tracking this, am going to close this out so we can track over there
